AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 15

Resources:
  ThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: thumbnail/
      Handler: thumbnail
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active
      Role: !GetAtt ThumbnailFunctionLambdaRole.Arn
      Events:
        SNSTopicEvent:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic
  ThumbnailFunctionLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: ThumbnailFunctionLambdaRolePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource:
                  - "*"
              - Effect: Allow
                Action:
                  - logs:PutLogEvents
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                Resource:
                  - "arn:aws:logs:*:*:*"
  SNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "TopicForThumbnailFunctionLambda"
      TopicName: "TopicForThumbnailFunctionLambda"
  SNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      PolicyDocument:
        Version: "2008-10-17"
        Id: "from_s3_policy_id"
        Statement:
          -
            Sid: SendToSns
            Effect: Allow
            Principal:
              AWS: "*"
            Action:
              SNS:Publish
            Resource: !Ref SNSTopic
            Condition:
              ArnLike:
                aws:SourceArn: arn:aws:s3:::tatsukoni-lambda-demo
      Topics: 
        - !Ref SNSTopic
